[ODS-4488] Fix broken composite features reported by the postman tests
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation pull request #130
Opened 2020-10-05 17:35 UTC by semalaiappan

2020-10-07 12:37 UTC, jamessmckay requested changes

2020-10-07 12:37 UTC, jamessmckay commented on Application/EdFi.Ods.Api.IntegrationTestHarness/Startup.cs
> +            AssemblyLoader.EnsureLoaded<Marker_EdFi_Ods_Profiles_Test>();
This change is not needed, we load all assemblies in the folder automatically now
```suggestion
```

2020-10-07 12:37 UTC, jamessmckay commented on Application/EdFi.Ods.Api.IntegrationTestHarness/Startup.cs
> +using EdFi.Ods.Profiles.Test;
```suggestion
```

2020-10-09 16:01 UTC, tbmeador-dlp requested changes
@semalaiappan when you get a chance there is still some unaddressed comments on this PR.

2020-10-09 18:25 UTC, tbmeador-dlp requested changes
@semalaiappan do we need these remaining changes or can we delete this branch now?

2020-10-13 15:22 UTC, tbmeador-dlp commented
reopening as these changes are required

2020-10-13 15:23 UTC, tbmeador-dlp approved these changes

2020-10-13 15:23 UTC, merged