[ODS-4297 , ODS-4287] Cleanup .net.cs files and pre-processor directives , Drop net48 support in class libraries
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation pull request #138
Opened 2020-10-13 10:36 UTC by BhanuprakashThunga

2020-10-13 19:47 UTC, blmeyers requested changes
Make sure we're cleaning up all the code we're deleting, not just excluding it. Revisit all the csproj files.  There are still cases of framework checks sticking around, both for standard and for net48.  After this PR there should be no more conditional includes in the csproj files.
There are still 8 files in this repo with #if conditionals.  Please make sure we're removing the conditional if its for NETSTANDARD or CORE, and that we're deleting the file if its for net48.

2020-10-13 19:47 UTC, blmeyers commented on Application/EdFi.Ods.Features.OwnershipBasedAuthorization/Container/Modules/OwnershipBasedAuthorizationModule.cs
>  using Autofac;
This file is missing a copyright header, please fix.

2020-10-13 19:47 UTC, blmeyers commented on Application/EdFi.Ods.Features.OwnershipBasedAuthorization/EdFi.Ods.Features.OwnershipBasedAuthorization.csproj
> +  </ItemGroup>
```suggestion
```

2020-10-14 21:03 UTC, jamessmckay approved these changes

2020-10-15 00:17 UTC, blmeyers approved these changes

2020-10-15 00:18 UTC, merged