[ODS-4565] Update SwaggerUI Powershell Installer for .NET core apps
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation pull request #145
Opened 2020-10-16 07:49 UTC by BhanuprakashThunga

2020-10-16 16:21 UTC, tbmeador-dlp requested changes
once installer are you able to open the website?

2020-10-16 16:21 UTC, tbmeador-dlp commented on Scripts/NuGet/EdFi.Installer.SwaggerUI/Install-EdFiOdsSwaggerUI.psm1
>          }
we need to update this to match the new format:
```suggestion
        $appSettings = @{
            WebApiVersionUrl = $Config.WebApiMetadataUrl
            SwaggerUIOptions = @{
                OAuthConfigObject = @{
                    ClientId     = $Config.PrePopulatedKey
                    ClientSecret = $Config.PrePopulatedSecret
                }
            }
        }
```

2020-10-16 16:25 UTC, tbmeador-dlp commented
you can use package version `5.1.0-b12868` to test this one.

2020-10-19 15:41 UTC, tbmeador-dlp requested changes
A few small things that I missed on the last round:

Lets remove the mandatory attribute here:
https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/blob/bc57c003aa7efcd168ecf47bb5f97980786f88eb/Scripts/NuGet/EdFi.Installer.SwaggerUI/Install-EdFiOdsSwaggerUI.psm1#L84-L86
and we can mark it as obsolete:
```powershell
[Obsolete("This parameter is deprecated, and will be removed in the near future.")]
```

We should also update the test.ps1 and remove this parameter.

2020-10-19 15:41 UTC, tbmeador-dlp commented on Scripts/NuGet/EdFi.Installer.SwaggerUI/Install-EdFiOdsSwaggerUI.psm1
> +            WebApiVersionUrl = $Config.WebApiMetadataUrl
```suggestion
            WebApiVersionUrl = $Config.WebApiVersionUrl
```

2020-10-21 17:09 UTC, jamessmckay approved these changes

2020-10-21 17:10 UTC, merged