[ODS-4707] Support Configuration to Drive Reverse Proxy Support
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation pull request #206
Opened 2020-12-16 16:29 UTC by raghuramakrishna

2020-12-16 21:57 UTC, jamessmckay requested changes
This implementation is not correct. What we need changed is in the startup class. of the application. In this case we need to wrap the registration of the proxy support with the check from the configuration. Secondly, then the AllForwarded headers being allowed needs to change to an logical or statement on the headers we are interested in.

2020-12-17 18:31 UTC, jamessmckay requested changes
This looks good, however we need a pull request for the docker config being updated.

2020-12-17 18:33 UTC, jamessmckay requested changes
Note, I just noticed the RequestExtensions shoud probably have the boolean value passed down from the controllers. The controllers should check for the key out of the config.

2020-12-23 20:48 UTC, blmeyers approved these changes

2020-12-28 21:24 UTC, tnunnerydl approved these changes

2021-01-04 21:33 UTC, merged