[ODS-4949] Modify Load Tools Script to Use dotnet CLI.
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation pull request #286
Opened 2021-06-09 13:39 UTC by tnunnerydl

2021-06-09 16:16 UTC, tbmeador-dlp requested changes
Looks good overall. Does it work if we remove the `Invoke-RestoreLoadToolsPackages` function? They should be restored automatically by the `dotnet build` in the `Invoke-BuildLoadTools` function.

2021-06-09 16:16 UTC, tbmeador-dlp commented on logistics/scripts/modules/LoadTools.psm1
> +        Write-Host 'Ensure that the Visual Studio SDK is installed.'
can we remove this? it doesn't make sense here.
```suggestion
```

2021-06-10 00:13 UTC, tnunnerydl commented
It worked after removing Invoke-RestoreLoadToolsPackages.

2021-06-10 16:55 UTC, tbmeador-dlp requested changes

2021-06-10 16:55 UTC, tbmeador-dlp commented on logistics/scripts/modules/LoadTools.psm1
> +    if ((Get-DeploymentSettings).Engine -eq 'PostgreSQL') { $buildConfiguration = 'Npgsql' }
This line seems to be causing the template builds to fail. We don't have a `Npgsql` build configuration anymore so we should be able to remove it.
```suggestion
```

2021-06-10 17:41 UTC, tbmeador-dlp approved these changes

2021-06-10 20:50 UTC, merged