[ODS-5033] Create Template builds for TPDM Core
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation pull request #328
Opened 2021-09-24 15:33 UTC by raghuramakrishna

2021-09-24 16:25 UTC, tbmeador-dlp requested changes

2021-09-27 10:07 UTC, raghuramakrishna commented on DatabaseTemplate/Modules/create-tpdm-minimal-template.psm1
> +Set-Alias -Scope Global initmin Initialize-MinimalTemplate
removed

2021-09-27 10:17 UTC, raghuramakrishna commented on DatabaseTemplate/Modules/create-tpdm-minimal-template.psm1
> +        [string] $samplePath = "$PSScriptRoot/../../../Ed-Fi-TPDM-Extension/",
updated

2021-09-27 10:20 UTC, raghuramakrishna commented on DatabaseTemplate/Modules/create-tpdm-minimal-template.psm1
> +    $config.packageNuspecName = "EdFi.Ods.Minimal.Template.TPDM"
updated

2021-09-27 10:21 UTC, raghuramakrishna commented on DatabaseTemplate/Modules/create-tpdm-minimal-template.psm1
> +        PS> Initialize-PopulatedTempalate -samplePath "C:\edfi\Ed-Fi-Standard\v3.2\"
updated

2021-09-28 17:05 UTC, tbmeador-dlp approved these changes

2021-09-28 17:05 UTC, merged