[ODS-5353] GitHub Actions: Setup EdFi.Ods.Standard build
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation pull request #441
Opened 2022-05-27 22:07 UTC by semalaiappan

2022-06-01 18:48 UTC, bptillman requested changes
All the other changes look good, but I did have one comment about making sure the PR action will checkout both branches correctly

2022-06-07 15:48 UTC, ericstockdale approved these changes

2022-06-07 15:50 UTC, ericstockdale approved these changes

2022-06-07 16:32 UTC, bptillman approved these changes

2022-06-07 16:32 UTC, merged