[ODS-5372] Support PS 7.2 and Unix - Script group 3
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation pull request #501
Opened 2022-09-13 17:01 UTC by AxelMarquez

2022-09-16 23:16 UTC, bptillman commented
Making a general comment here since the file was not change. The settings-teamcity.psm1 file was in the list of files to check, and on line 18 I believe we need to change `$env:TEAMCITY_BUILD_PROPERTIES_FILE` to `[Environment]::TEAMCITY_BUILD_PROPERTIES_FILE`

2022-09-19 15:32 UTC, bptillman requested changes
Lots of good work here in moving everything over. I did have some comments on things I think still need to change, but please review them and let me know if any don't look right to you.

2022-09-19 16:01 UTC, AxelMarquez commented on logistics/scripts/modules/database/postgres-database-management.psm1
>      $packagePath = "$script:toolsPath/$script:packageName.$script:packageVersion"
`postgres-database-management.psm1` isn't completely migrated yet, [ODS-5373](https://tracker.ed-fi.org/browse/ODS-5373) will complete its migration.

2022-09-19 20:10 UTC, AxelMarquez commented on DatabaseTemplate/Modules/get-populated-from-web.ps1
> +& "$PSScriptRoot/../../logistics/scripts/modules/load-path-resolver.ps1"
Good catch, I moved them after the parameters but before the new use of Get-IsWindows

2022-09-19 20:10 UTC, AxelMarquez commented on DatabaseTemplate/Modules/get-template-from-web.ps1
> +& "$PSScriptRoot/../../logistics/scripts/modules/load-path-resolver.ps1"
Good catch, I moved them after the parameters but before the new use of Get-IsWindows

2022-09-19 20:11 UTC, AxelMarquez commented on logistics/scripts/modules/utility/xml-validation.psm1
>      param(
I agree, I replaced backslashes with slashes in comments.

2022-09-19 21:55 UTC, bptillman approved these changes

2022-09-19 21:55 UTC, merged