[ODS-5376] Support PS 7.2 and Unix - Script group 7
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation pull request #527
Opened 2022-10-13 21:01 UTC by ericstockdale

2022-10-17 22:03 UTC, bptillman requested changes
I tested things out and they look good in Windows and Linux. Just a few changes it looks like that need to be made here and then this PR is good to go.

2022-10-17 22:59 UTC, ericstockdale commented on DatabaseTemplate/Modules/create-database-template.psm1
>  & "$PSScriptRoot\..\..\logistics\scripts\modules\load-path-resolver.ps1"
updated

2022-10-18 00:20 UTC, ericstockdale commented on DatabaseTemplate/Modules/create-database-template.psm1
> +    $config.testHarnessExecutable = "$($config.outputFolder)/EdFi.Ods.Api.IntegrationTestHarness.exe"
updated

2022-10-18 15:50 UTC, bptillman approved these changes

2022-10-18 16:17 UTC, merged