[ODS-6118] Switch build setup for next release v7.2
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation pull request #865
Opened 2023-12-11 18:18 UTC by semalaiappan

2023-12-13 15:23 UTC, simpat-jesus requested changes
Update EdFi.Ods.Common version in configuration.packages.json, currently has version 7.1.2

2023-12-14 15:41 UTC, semalaiappan commented
> EdFi.Ods.Common

Fix it now . Thanks

2023-12-14 16:19 UTC, simpat-jesus approved these changes

2023-12-14 16:25 UTC, vimayya approved these changes

2023-12-14 16:35 UTC, merged