[ODS-6313] Scorecard supply-chain security Workflow Added
Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation pull request #982
Opened 2024-04-06 02:14 UTC by semalaiappan

2024-04-09 20:14 UTC, simpat-jesus requested changes
Open a ticket to fix https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/security/code-scanning?query=pr%3A982+is%3Aopen

2024-04-09 20:14 UTC, simpat-jesus commented on .github/workflows/Scorecard supply-chain security.yml
> +  pull_request:
Replace with a scheduled run

2024-04-10 13:07 UTC, semalaiappan commented
> Open a ticket to fix https://github.com/Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation/security/code-scanning?query=pr%3A982+is%3Aopen

New ticket created https://tracker.ed-fi.org/browse/ODS-6328

2024-04-10 13:10 UTC, semalaiappan commented on .github/workflows/Scorecard supply-chain security.yml
> +  pull_request:
Fixed it . Ready for Review

2024-04-10 17:13 UTC, vimayya approved these changes

2024-04-10 17:18 UTC, merged